#!/usr/bin/env node
// Regenerates src/generated/types.ts from bam-core's JSON Schema export
// (P9.1). The Rust types are the source of truth; this script is the only
// place a hand edit to the generated file would be overwritten from.
import { execFileSync } from "node:child_process";
import { compile } from "json-schema-to-typescript";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(root);

export function exportSchemas() {
  const stdout = execFileSync(
    "cargo",
    ["run", "--quiet", "--example", "export_api_schema", "-p", "bam-core"],
    { cwd: repoRoot, maxBuffer: 64 * 1024 * 1024 },
  );
  return JSON.parse(stdout.toString("utf8"));
}

// Each `schema_for!` root is self-contained with its own nested `definitions`
// (e.g. every request that carries a `Predicate` re-declares `Predicate`,
// `FieldId`, ...). Compiling each root in its own `compile()` call would
// re-emit those shared types once per root and collide on the name.
// Instead, merge every root and every nested definition into one shared
// `definitions` map and compile a single synthetic root that `$ref`s all of
// them, so json-schema-to-typescript dedups by construction.
export async function generate(schemas) {
  const defs = {};
  for (const [name, schema] of Object.entries(schemas)) {
    const { definitions, ...rest } = schema;
    defs[name] = rest;
    Object.assign(defs, definitions ?? {});
  }

  const root = {
    definitions: defs,
    oneOf: Object.keys(schemas)
      .sort()
      .map((name) => ({ $ref: `#/definitions/${name}` })),
  };

  const banner = `// AUTO-GENERATED by frontend/scripts/gen-types.mjs from bam-core's JSON
// Schema export — do not hand-edit. Re-run \`npm run gen:types\`.
`;
  const ts = await compile(root, "ApiTypes", {
    bannerComment: "",
    additionalProperties: false,
  });
  return banner + "\n" + ts;
}

async function main() {
  const schemas = exportSchemas();
  const ts = await generate(schemas);
  const outPath = join(root, "src", "generated", "types.ts");
  const fs = await import("node:fs");
  fs.writeFileSync(outPath, ts);
  console.log(`wrote ${outPath}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
